spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    queue:
      twitter: twitter-stream
    exchange:
      twitter: twitter-exchange
    routing_key:
      track: track.*
